services:
  db:
    image: mysql:8.0
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo-network

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: todo_db
    depends_on:
      - db
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # This tells React which URL to call for the backend API
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  db_data:

networks:
  todo-network:
    driver: bridge
